version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch-curl
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          ls -l /usr/local
          mkdir -p /usr/local/bin
          curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      - run: docker-compose run --rm app make test
